site_name: Microbial Genomics & Metagenomics Training Course
site_description: Hands-on training course for microbial genomics and metagenomics in clinical and public health applications
# Force rebuild 2025-09-02-v2
site_author: CIDRI-Africa
site_url: https://cidri-africa.github.io/microbial-genomics-training/

repo_name: CIDRI-Africa/microbial-genomics-training
repo_url: https://github.com/CIDRI-Africa/microbial-genomics-training

docs_dir: docs_src

copyright: Copyright &copy; 2024 CIDRI-Africa

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/dna
    repo: fontawesome/brands/github

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CIDRI-Africa
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CIDRIAfrica

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: CIDRI-Africa
      repo: microbial-genomics-training
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - glightbox

nav:
  - Home: index.md
  - Course Information:
    - Overview: course/overview.md
    - Learning Objectives: course/objectives.md
    - Prerequisites: course/prerequisites.md
    - Schedule: course/schedule.md
    - Setup: course/setup.md
  - Daily Modules:
    - Day 1 - Welcome to the Course!: modules/day1/index.md
    - Day 2 - Introduction to Commandline, High Performance Computing, & Quality Control: modules/day2/index.md
    - Day 3 - Genomic Characterization: modules/day3/index.md
    - Day 4 - Genomic Characterization: modules/day4/index.md
    - Day 5 - Nextflow Pipeline Development: modules/day5/index.md
    - Day 6 - Nextflow Pipeline Development & Version Control with GitHub: modules/day6/index.md
    - Day 7 - Advanced Nextflow & Version Control with GitHub: modules/day7/index.md
    - Day 8 - Comparative Genomics: modules/day8/index.md
    - Day 9 - Bring your own data: modules/day9/index.md
    - Day 10 - Wrap-up session: modules/day10/index.md
  - Resources:
    - Datasets: datasets.md
    - Troubleshooting: troubleshooting.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js